apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APPLICATION_NAME
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $APPLICATION_NAME
  template:
    metadata:
      labels:
        app: $APPLICATION_NAME
    spec:
      containers:
        - name: $APPLICATION_NAME
          image: $CONTAINER_REGISTRY_IMAGE
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_DOTNET_API_URL
              valueFrom:
                secretKeyRef:
                  name: $SECRETS_FILE
                  key: REACT_APP_DOTNET_API_URL

