apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
spec:
  type: NodePort
  selector:
    app: $APPLICATION_NAME
  ports:
    - protocol: TCP
      port: 81        # The port exposed on the service
      targetPort: 3000          # The port your application is listening on in the container
      nodePort: 30082
